### ISSUE TITLE
Additional dbgProvider options

### ISSUE THREAD

**Issue by vanossj** [31i73/atom-dbg#7]
The Configure Debug Session panel works well for basic options, but for specific/less used dbgProvider options like environmental variable support (31i73/atom-dbg-gdb#10), remote target (31i73/atom-dbg-gdb#9), etc. I think an alternative solution is necessary.

Possibly options:
1. add optional .atom-debug.json, int the same vein as [atom-build](https://github.com/noseglid/atom-build#specify-a-custom-build-command)
2. add debug options to [projects.cson](https://github.com/danielbrodin/atom-project-manager#example) file

I prefer adding an .atom-debug.json file and avoid dependency on another atom package.

It would be neat if Atom could generate a page for modifying debug options. similar to how it generates the Settings pane for package config.

**Comment by ProPuke** [comment]
Yeah, per-project debug options are definitely something I'd like.

I've been watching https://github.com/atom/atom/issues/5168 (Per-project config settings - project-local config files override the global atom config file), in case something comes of it. But it doesn't seem to have gathered much more attention. I'd like to work within atoms design rather than adding custom files where possible, but seems it might not be.

Option 1 definitely sounds like the better option to me (mostly cos I use a different package for managing my projects, and am not subscribed to project-manager's way of doing things; and believe dbg should try to be neutral if there is no clear lead on the best way to approach things)

For the config file I was seeing something akin to:

```
client:
	debugger: 'gdb'
	cwd: 'client'
	path: 'client/bin'
	args: ['--connect', '1234']

server:
	debugger: 'gdb'
	cwd: 'server'
	path: 'server/bin'
	args: ['--port', '1234']
```

(So a list of named debug configurations)

How does that sound?

A gui for configuring the settings sounds neat, but It's probably something I'd give less priority, comparatively (unless somebody else decides to add it :D)
